### ISSUE TITLE
genco tokenization of rust lifetimes broken in 0.16

### ISSUE THREAD

**Issue by dvc94ch** [udoprog/genco#21]
So it's nice that it builds on stable, but it doesn't quite work with lifetimes. `' static` is not valid rust, rustc complains that a "character literal may only contain one codepoint".

**Comment by udoprog** [comment]
Cheers. There might not be enough info to resolve this. Apparently the `'` punctuation might not have joined spacing. But I'll look into it to see if there's anything that can be done.

Cheers!

**Comment by udoprog** [comment]
Should be fixed now in `0.16.1`!

**Comment by dvc94ch** [comment]
Gave it a try. The fix fixes the life time issue but found another one. Identifiers are split in weird ways: `tmp0 _0` should be `tmp0_0`.

**Comment by udoprog** [comment]
Yeah. I don't think there's much to be done there unfortunately. We can't tell when there is some space between two things and no space.

To construct an identifier that is concatenated we'd have to resort to some form of markup or formatting the identifier online, like: `#(format!("{}{}", "tmp0", "_0"))`.
