### ISSUE TITLE
Support C

### ISSUE THREAD

**Issue by isaiahpettingill** [udoprog/genco#22]
It would be awesome to add support for the c programming language. That way c could be used as a compile target for other languages or just for code generation. ANSI C99 support would be great. 

You could use `#include`s for imports.

**Comment by udoprog** [comment]
Adding support for another language flavor is pretty straight forward if anyone wants to take a stab at it.

If anyone wants to take a stab at it, see for example Go: https://github.com/udoprog/genco/blob/main/src/lang/go.rs

**Comment by ajwerner** [comment]
Now that this is merged, any interest in cutting a release and closing this issue?

**Comment by udoprog** [comment]
I am waiting for a resolution to #39. Once that is in place I'll definitely want to make a release.

**Comment by udoprog** [comment]
Released now in 0.17.6.
