### ISSUE TITLE
Add "import xxxx.xxx" support on java class generation.

### ISSUE THREAD

**Issue by sidneywang** [udoprog/genco#3]
How can I add "import xxx.xxx.xx" when generate a class file.

**Comment by sidneywang** [comment]
Is there any convenient way to do that?
I use toks! to make it.

**Comment by udoprog** [comment]
Yeah, you use imported tokens:
https://github.com/udoprog/genco/blob/master/src/java/mod.rs#L502

Examples here:
https://github.com/reproto/reproto/blob/master/lib/backend-java/src/compiler.rs#L82
