### ISSUE TITLE
Generic code generation possible 

### ISSUE THREAD

**Issue by Deaths-Door** [udoprog/genco#42]
I am need of generic code generation for multiple languages so eg give data like function name parms and Parms types etc and I need to generate the function , I have read the documentation but failed to find anything like that , is there a section I missed or does this lib not support this at all?

**Comment by udoprog** [comment]
Sorry, generic code generation is not possible since `FormatInto` et. al. always need to be parameterized by the language.

What I did in [`reproto`](https://github.com/reproto) was to have different codegen backends at a higher level that I abstracted over.
