### ISSUE TITLE
Upcoming breakage in Rust

### ISSUE THREAD

**Issue by Mark-Simulacrum** [udoprog/genco#9]
The Rust compiler will soon be breaking crates that depended on unsound behavior accepted by the old borrow checker; the new implementation catches more cases. A recent crater run across the ecosystem found that this crate breaks (https://crater-reports.s3.amazonaws.com/beta-1.40-1/beta-2019-11-06/reg/genco-0.3.30/log.txt); this is a notification of that. Let me know if you have more questions!

**Comment by udoprog** [comment]
Awesome, thanks for the heads up and sorry for the slow reply. I'll push a fix asap :D.
